// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokerTrainerApi.DrawRanges.Repository;

#nullable disable

namespace PokerTrainerAPI.Migrations
{
    [DbContext(typeof(PokerDbContext))]
    partial class PokerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PokerTrainerApi.DrawRanges.Repository.PokerRangeDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SpotKey")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PokerRanges");
                });

            modelBuilder.Entity("PokerTrainerApi.DrawRanges.Repository.PokerRangeEntryDao", b =>
                {
                    b.Property<int>("RangeId")
                        .HasColumnType("int");

                    b.Property<int>("HandKey")
                        .HasColumnType("int");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<int?>("PokerRangeDaoId")
                        .HasColumnType("int");

                    b.HasKey("RangeId", "HandKey");

                    b.HasIndex("PokerRangeDaoId");

                    b.ToTable("RangeEntries");
                });

            modelBuilder.Entity("PokerTrainerApi.DrawRanges.Repository.PokerRangeEntryDao", b =>
                {
                    b.HasOne("PokerTrainerApi.DrawRanges.Repository.PokerRangeDao", null)
                        .WithMany("Entries")
                        .HasForeignKey("PokerRangeDaoId");
                });

            modelBuilder.Entity("PokerTrainerApi.DrawRanges.Repository.PokerRangeDao", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
