using System.Text.Json.Serialization;

public enum PokerHandKey
{
    [JsonStringEnumMemberName("AA")]
    AA,
    [JsonStringEnumMemberName("AKs")]
    AKs,
    [JsonStringEnumMemberName("AKo")]
    AKo,
    [JsonStringEnumMemberName("AQs")]
    AQs,
    [JsonStringEnumMemberName("AQo")]
    AQo,
    [JsonStringEnumMemberName("AJs")]
    AJs,
    [JsonStringEnumMemberName("AJo")]
    AJo,
    [JsonStringEnumMemberName("ATs")]
    ATs,
    [JsonStringEnumMemberName("ATo")]
    ATo,
    [JsonStringEnumMemberName("A9s")]
    A9s,
    [JsonStringEnumMemberName("A9o")]
    A9o,
    [JsonStringEnumMemberName("A8s")]
    A8s,
    [JsonStringEnumMemberName("A8o")]
    A8o,
    [JsonStringEnumMemberName("A7s")]
    A7s,
    [JsonStringEnumMemberName("A7o")]
    A7o,
    [JsonStringEnumMemberName("A6s")]
    A6s,
    [JsonStringEnumMemberName("A6o")]
    A6o,
    [JsonStringEnumMemberName("A5s")]
    A5s,
    [JsonStringEnumMemberName("A5o")]
    A5o,
    [JsonStringEnumMemberName("A4s")]
    A4s,
    [JsonStringEnumMemberName("A4o")]
    A4o,
    [JsonStringEnumMemberName("A3s")]
    A3s,
    [JsonStringEnumMemberName("A3o")]
    A3o,
    [JsonStringEnumMemberName("A2s")]
    A2s,
    [JsonStringEnumMemberName("A2o")]
    A2o,
    [JsonStringEnumMemberName("KK")]
    KK,
    [JsonStringEnumMemberName("KQs")]
    KQs,
    [JsonStringEnumMemberName("KQo")]
    KQo,
    [JsonStringEnumMemberName("KJs")]
    KJs,
    [JsonStringEnumMemberName("KJo")]
    KJo,
    [JsonStringEnumMemberName("KTs")]
    KTs,
    [JsonStringEnumMemberName("KTo")]
    KTo,
    [JsonStringEnumMemberName("K9s")]
    K9s,
    [JsonStringEnumMemberName("K9o")]
    K9o,
    [JsonStringEnumMemberName("K8s")]
    K8s,
    [JsonStringEnumMemberName("K8o")]
    K8o,
    [JsonStringEnumMemberName("K7s")]
    K7s,
    [JsonStringEnumMemberName("K7o")]
    K7o,
    [JsonStringEnumMemberName("K6s")]
    K6s,
    [JsonStringEnumMemberName("K6o")]
    K6o,
    [JsonStringEnumMemberName("K5s")]
    K5s,
    [JsonStringEnumMemberName("K5o")]
    K5o,
    [JsonStringEnumMemberName("K4s")]
    K4s,
    [JsonStringEnumMemberName("K4o")]
    K4o,
    [JsonStringEnumMemberName("K3s")]
    K3s,
    [JsonStringEnumMemberName("K3o")]
    K3o,
    [JsonStringEnumMemberName("K2s")]
    K2s,
    [JsonStringEnumMemberName("K2o")]
    K2o,
    [JsonStringEnumMemberName("QQ")]
    QQ,
    [JsonStringEnumMemberName("QJs")]
    QJs,
    [JsonStringEnumMemberName("QJo")]
    QJo,
    [JsonStringEnumMemberName("QTs")]
    QTs,
    [JsonStringEnumMemberName("QTo")]
    QTo,
    [JsonStringEnumMemberName("Q9s")]
    Q9s,
    [JsonStringEnumMemberName("Q9o")]
    Q9o,
    [JsonStringEnumMemberName("Q8s")]
    Q8s,
    [JsonStringEnumMemberName("Q8o")]
    Q8o,
    [JsonStringEnumMemberName("Q7s")]
    Q7s,
    [JsonStringEnumMemberName("Q7o")]
    Q7o,
    [JsonStringEnumMemberName("Q6s")]
    Q6s,
    [JsonStringEnumMemberName("Q6o")]
    Q6o,
    [JsonStringEnumMemberName("Q5s")]
    Q5s,
    [JsonStringEnumMemberName("Q5o")]
    Q5o,
    [JsonStringEnumMemberName("Q4s")]
    Q4s,
    [JsonStringEnumMemberName("Q4o")]
    Q4o,
    [JsonStringEnumMemberName("Q3s")]
    Q3s,
    [JsonStringEnumMemberName("Q3o")]
    Q3o,
    [JsonStringEnumMemberName("Q2s")]
    Q2s,
    [JsonStringEnumMemberName("Q2o")]
    Q2o,
    [JsonStringEnumMemberName("JJ")]
    JJ,
    [JsonStringEnumMemberName("JTs")]
    JTs,
    [JsonStringEnumMemberName("JTo")]
    JTo,
    [JsonStringEnumMemberName("J9s")]
    J9s,
    [JsonStringEnumMemberName("J9o")]
    J9o,
    [JsonStringEnumMemberName("J8s")]
    J8s,
    [JsonStringEnumMemberName("J8o")]
    J8o,
    [JsonStringEnumMemberName("J7s")]
    J7s,
    [JsonStringEnumMemberName("J7o")]
    J7o,
    [JsonStringEnumMemberName("J6s")]
    J6s,
    [JsonStringEnumMemberName("J6o")]
    J6o,
    [JsonStringEnumMemberName("J5s")]
    J5s,
    [JsonStringEnumMemberName("J5o")]
    J5o,
    [JsonStringEnumMemberName("J4s")]
    J4s,
    [JsonStringEnumMemberName("J4o")]
    J4o,
    [JsonStringEnumMemberName("J3s")]
    J3s,
    [JsonStringEnumMemberName("J3o")]
    J3o,
    [JsonStringEnumMemberName("J2s")]
    J2s,
    [JsonStringEnumMemberName("J2o")]
    J2o,
    [JsonStringEnumMemberName("TT")]
    TT,
    [JsonStringEnumMemberName("T9s")]
    T9s,
    [JsonStringEnumMemberName("T9o")]
    T9o,
    [JsonStringEnumMemberName("T8s")]
    T8s,
    [JsonStringEnumMemberName("T8o")]
    T8o,
    [JsonStringEnumMemberName("T7s")]
    T7s,
    [JsonStringEnumMemberName("T7o")]
    T7o,
    [JsonStringEnumMemberName("T6s")]
    T6s,
    [JsonStringEnumMemberName("T6o")]
    T6o,
    [JsonStringEnumMemberName("T5s")]
    T5s,
    [JsonStringEnumMemberName("T5o")]
    T5o,
    [JsonStringEnumMemberName("T4s")]
    T4s,
    [JsonStringEnumMemberName("T4o")]
    T4o,
    [JsonStringEnumMemberName("T3s")]
    T3s,
    [JsonStringEnumMemberName("T3o")]
    T3o,
    [JsonStringEnumMemberName("T2s")]
    T2s,
    [JsonStringEnumMemberName("T2o")]
    T2o,
    [JsonStringEnumMemberName("99")]
    _99,
    [JsonStringEnumMemberName("98s")]
    _98s,
    [JsonStringEnumMemberName("98o")]
    _98o,
    [JsonStringEnumMemberName("97s")]
    _97s,
    [JsonStringEnumMemberName("97o")]
    _97o,
    [JsonStringEnumMemberName("96s")]
    _96s,
    [JsonStringEnumMemberName("96o")]
    _96o,
    [JsonStringEnumMemberName("95s")]
    _95s,
    [JsonStringEnumMemberName("95o")]
    _95o,
    [JsonStringEnumMemberName("94s")]
    _94s,
    [JsonStringEnumMemberName("94o")]
    _94o,
    [JsonStringEnumMemberName("93s")]
    _93s,
    [JsonStringEnumMemberName("93o")]
    _93o,
    [JsonStringEnumMemberName("92s")]
    _92s,
    [JsonStringEnumMemberName("92o")]
    _92o,
    [JsonStringEnumMemberName("88")]
    _88,
    [JsonStringEnumMemberName("87s")]
    _87s,
    [JsonStringEnumMemberName("87o")]
    _87o,
    [JsonStringEnumMemberName("86s")]
    _86s,
    [JsonStringEnumMemberName("86o")]
    _86o,
    [JsonStringEnumMemberName("85s")]
    _85s,
    [JsonStringEnumMemberName("85o")]
    _85o,
    [JsonStringEnumMemberName("84s")]
    _84s,
    [JsonStringEnumMemberName("84o")]
    _84o,
    [JsonStringEnumMemberName("83s")]
    _83s,
    [JsonStringEnumMemberName("83o")]
    _83o,
    [JsonStringEnumMemberName("82s")]
    _82s,
    [JsonStringEnumMemberName("82o")]
    _82o,
    [JsonStringEnumMemberName("77")]
    _77,
    [JsonStringEnumMemberName("76s")]
    _76s,
    [JsonStringEnumMemberName("76o")]
    _76o,
    [JsonStringEnumMemberName("75s")]
    _75s,
    [JsonStringEnumMemberName("75o")]
    _75o,
    [JsonStringEnumMemberName("74s")]
    _74s,
    [JsonStringEnumMemberName("74o")]
    _74o,
    [JsonStringEnumMemberName("73s")]
    _73s,
    [JsonStringEnumMemberName("73o")]
    _73o,
    [JsonStringEnumMemberName("72s")]
    _72s,
    [JsonStringEnumMemberName("72o")]
    _72o,
    [JsonStringEnumMemberName("66")]
    _66,
    [JsonStringEnumMemberName("65s")]
    _65s,
    [JsonStringEnumMemberName("65o")]
    _65o,
    [JsonStringEnumMemberName("64s")]
    _64s,
    [JsonStringEnumMemberName("64o")]
    _64o,
    [JsonStringEnumMemberName("63s")]
    _63s,
    [JsonStringEnumMemberName("63o")]
    _63o,
    [JsonStringEnumMemberName("62s")]
    _62s,
    [JsonStringEnumMemberName("62o")]
    _62o,
    [JsonStringEnumMemberName("55")]
    _55,
    [JsonStringEnumMemberName("54s")]
    _54s,
    [JsonStringEnumMemberName("54o")]
    _54o,
    [JsonStringEnumMemberName("53s")]
    _53s,
    [JsonStringEnumMemberName("53o")]
    _53o,
    [JsonStringEnumMemberName("52s")]
    _52s,
    [JsonStringEnumMemberName("52o")]
    _52o,
    [JsonStringEnumMemberName("44")]
    _44,
    [JsonStringEnumMemberName("43s")]
    _43s,
    [JsonStringEnumMemberName("43o")]
    _43o,
    [JsonStringEnumMemberName("42s")]
    _42s,
    [JsonStringEnumMemberName("42o")]
    _42o,
    [JsonStringEnumMemberName("33")]
    _33,
    [JsonStringEnumMemberName("32s")]
    _32s,
    [JsonStringEnumMemberName("32o")]
    _32o,
    [JsonStringEnumMemberName("22")]
    _22,
}